

interface ReportDashboardProps {
    htmlContent: string;
    onReset: () => void;
}

export function ReportDashboard({ htmlContent, onReset }: ReportDashboardProps) {
    return (
        <div className="report-container" style={{ padding: '2rem 0 4rem', animation: 'fadeIn 0.5s ease-out' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
                <div>
                    <h2 style={{ fontSize: '2rem', fontWeight: '700', color: 'var(--color-neutral-900)' }}>Analysis Report</h2>
                    <p style={{ color: 'var(--color-neutral-500)' }}>Generated by MarketMind AI</p>
                </div>
                <button
                    onClick={onReset}
                    style={{
                        padding: '0.75rem 1.5rem',
                        border: '1px solid var(--color-neutral-300)',
                        backgroundColor: 'white',
                        borderRadius: 'var(--radius-md)',
                        fontWeight: '600',
                        color: 'var(--color-neutral-700)',
                        cursor: 'pointer',
                        transition: 'var(--transition-normal)'
                    }}
                    onMouseOver={(e) => e.currentTarget.style.backgroundColor = 'var(--color-neutral-50)'}
                    onMouseOut={(e) => e.currentTarget.style.backgroundColor = 'white'}
                >
                    New Analysis
                </button>
            </div>

            <div
                className="prose"
                style={{
                    background: 'white',
                    padding: '2.5rem',
                    borderRadius: 'var(--radius-md)',
                    boxShadow: 'var(--shadow-sm)',
                    border: '1px solid var(--color-neutral-200)',
                    marginTop: '1.5rem',
                    lineHeight: '1.6',
                    color: 'var(--color-neutral-800)'
                }}
                dangerouslySetInnerHTML={{ __html: htmlContent }}
            />

            <style>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        /* Basic styling for the injected HTML */
        .prose h1 { font-size: 1.875rem; font-weight: 700; margin-bottom: 1.5rem; color: var(--color-neutral-900); }
        .prose h2 { font-size: 1.5rem; font-weight: 600; margin-top: 2rem; margin-bottom: 1rem; color: var(--color-neutral-900); border-bottom: 1px solid var(--color-neutral-200); padding-bottom: 0.5rem; }
        .prose h3 { font-size: 1.25rem; font-weight: 600; margin-top: 1.5rem; margin-bottom: 0.75rem; color: var(--color-neutral-900); }
        .prose p { margin-bottom: 1rem; }
        .prose ul, .prose ol { margin-bottom: 1rem; padding-left: 1.5rem; }
        .prose li { margin-bottom: 0.5rem; }
        .prose strong { fontWeight: 600; color: var(--color-neutral-900); }
        .prose blockquote { border-left: 4px solid var(--color-primary-500); padding-left: 1rem; font-style: italic; color: var(--color-neutral-600); margin: 1.5rem 0; }
        .prose table { width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; }
        .prose th, .prose td { border: 1px solid var(--color-neutral-300); padding: 0.75rem; text-align: left; }
        .prose th { background-color: var(--color-neutral-100); font-weight: 600; }
        .prose .headline { font-size: 1.25rem; font-weight: bold; margin-top: 1.5rem; margin-bottom: 0.5rem; color: var(--color-primary-700); }
        .prose .paragraph { margin-bottom: 1rem; }
        .prose .bullet-item { margin-left: 1rem; margin-bottom: 0.5rem; display: flex; align-items: flex-start; }
        .prose .bullet-item span { margin-right: 0.5rem; color: var(--color-primary-600); font-weight: bold; }

        /* Hide elements from the raw HTML that might interfere or look bad */
        .prose .btn-container { display: none; } 
      `}</style>
        </div>
    );
}
